name = "Arblib"
uuid = "fb37089c-8514-4489-9461-98f9c8763369"
authors = ["Marek Kaluba <kalmar@amu.edu.pl>", "Sascha Timme <Sascha Timme <timme@math.tu-berlin.de>", "Joel Dahne <joel@dahne.eu>"]
version = "0.2.1"

[deps]
Arb_jll = "d9960996-1013-53c9-9ba4-74a4155039c3"
FLINT_jll = "e134572f-a0d5-539d-bddf-3cad8db41a82"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
Arb_jll = "2.18.1"
FLINT_jll = "2.6.3"
julia = "1.3"
